'use strict';
(()=>{
const chars=[
['mara','정비공 마라','균형형 · 초보자 추천',100,1,1,'pistol','현장 개조: 제작 비용과 과부하 페널티 감소','repair_drone',1],
['kane','탈주병 케인','연속 처치 · 공격형',90,1.05,0,'carbine','전투 집중: 연속 처치 시 발사·재장전·이동 증가','tactical_reload',1],
['nova','실험체 노바','상태 이상 · 고위험',80,1,0,'arc','불안정 세포: 서로 다른 상태 이상 결합 시 변이 반응','mutation',1],
['rex','밀수업자 렉스','경제 · 결함 거래',95,1,0,'saw','뒷거래: 가격 감소, 결함 상품, 판매가 증가','reroll',1],
['shell','셸-07','에너지 생존 · 비밀',70,1.08,3,'beam','기계 신체: 회복 대신 에너지·방어판, 과열 강화','hack',0]
].map(x=>({id:x[0],name:x[1],role:x[2],hp:x[3],speed:x[4],shield:x[5],weapon:x[6],passive:x[7],active:x[8],unlock:!!x[9]}));
const w=[
['pistol','서비스 피스톨','semi',18,.24,10,1.15,760,1,'균형형 · 완벽 재장전 첫 탄 치명타'],['carbine','버스트 카빈','burst',11,.32,24,1.45,780,3,'3점사 · 안정적인 중거리'],['smg','체인 SMG','auto',7,.075,36,1.7,720,1,'연속 명중 시 연사 증가'],['shotgun','브리치 샷건','spread',7,.75,5,1.8,560,8,'근거리 산탄과 강한 넉백'],['rail','레일 랜서','charge',90,1.05,4,1.9,1100,1,'충전 관통 · 단일 고화력'],['rotary','로터리 캐논','spin',9,.07,80,2.7,760,1,'회전 가속 · 높은 과열'],['grenade','파편 발사기','grenade',48,.82,4,2.1,430,1,'범위 폭발 · 장애물 무시'],['arc','아크 프로젝터','chain',8,.13,60,1.9,520,1,'전기 연쇄 · 다중 대상'],['beam','빔 커터','beam',16,.08,100,2.2,900,1,'지속 조준 · 열 기반'],['saw','톱날 캐스터','ricochet',24,.38,8,1.5,600,1,'벽 도탄 최대 3회'],['drone','드론 컨트롤러','drone',13,.42,12,1.7,650,2,'지원 드론 2기'],['hammer','압축 해머','melee',65,.72,1,.5,170,1,'근접 충격 · 탄환 반사']
].map(x=>({id:x[0],name:x[1],kind:x[2],damage:x[3],rate:x[4],mag:x[5],reload:x[6],speed:x[7],count:x[8],desc:x[9]}));
const B=[
['precision','정밀 총열',{spread:.65,bulletSpeed:1.15,fireRate:.92},['정밀']],['scatter','확산 총열',{projectiles:2,damage:.75,spread:1.55},['산탄']],['pierce','관통 총열',{pierce:2},['관통']],['bounce','반사 총열',{bounce:2,damage:1.2,bulletSpeed:.9},['도탄']],['explosive','폭발 총열',{explosion:46,damage:.8},['폭발']],['long','장거리 총열',{range:1.4,damage:1.15},['장거리']],['cut','절단 총열',{size:1.65,ammoUse:1.25},['절단']],['homing','유도 총열',{homing:.11,bulletSpeed:.9},['유도']],['split','분열 총열',{split:2},['분열']],['recoil','역추진 총열',{damage:1.2,recoil:1},['중량']],['resonance','공명 총열',{resonance:1},['보스']],['unstable','불안정 총열',{unstable:1},['결함']]
].map(x=>({id:x[0],name:x[1],effects:x[2],tags:x[3],category:'총열'}));
const M=[
['large','대용량 탄창',{mag:1.6,reload:1.25},['탄약']],['light','경량 탄창',{mag:.75,reload:.65},['경량']],['lastboom','폭발 탄창',{mag:.75,lastExplosion:90},['폭발']],['reverse','역순 탄창',{firstShot:1.45},['정밀']],['compressed','압축 탄창',{ammoUse:2,damage:1.7,size:1.25},['중량']],['regen','재생 탄창',{killAmmo:.16,mag:.85},['회수']],['emergency','비상 탄창',{lowHpReload:.5},['생존']],['magnetic','자기 탄창',{reloadAbsorb:1},['신호']],['cross','교차 탄창',{alternating:1},['상태']],['reactive','반응 탄창',{hitReload:1},['반응']],['gamble','도박 탄창',{freeReload:.2},['결함']],['dual','이중 탄창',{halfReload:1},['탄약']]
].map(x=>({id:x[0],name:x[1],effects:x[2],tags:x[3],category:'탄창'}));
const C=[['fire','화염 코어','burn','화염'],['ice','냉각 코어','freeze','냉기'],['electric','전기 코어','shock','전기'],['acid','부식 코어','corrode','부식'],['bleed','출혈 코어','bleed','출혈'],['void','공허 코어','void','공허'],['impact','충격 코어','impact','충격'],['absorb','흡수 코어','absorb','보호막'],['photon','광자 코어','photon','정밀'],['clone','복제 코어','clone','복제'],['devour','포식 코어','devour','처치'],['reverse','역상 코어','return','회수']].map(x=>({id:x[0],name:x[1],status:x[2],tags:[x[3]],category:'코어'}));
const moduleBase=[
['ballistic','탄도 계산기','치명타 확률 증가','정밀','signal'],['fan','냉각 팬','열 감소 속도 증가','냉각','cool'],['ammo_box','보조 탄약함','최대 탄약 증가','탄약','ammo'],['absorber','충격 흡수대','반동·중량 페널티 감소','중량','power'],['medkit','긴급 의료팩','저체력 자동 회복','생존','signal'],['reactive_armor','반응 장갑','피격 시 적 밀어내기','반응','power'],['illegal_amp','불법 증폭기','피해와 받는 피해 증가','결함','power'],['magnet','회수용 자석','드롭 획득 범위 증가','회수','signal'],['hunter','사냥꾼 렌즈','고체력 적 추가 피해','보스','signal'],['execute','처형 프로토콜','저체력 일반 적 처형','처치','signal'],['shell_collector','빈 탄피 수집기','재장전 시 고철 획득','경제','ammo'],['mobile_gen','이동식 발전기','이동 거리로 액티브 충전','이동','power'],['fixed_gen','고정식 발전기','정지 사격 공격력 증가','정밀','power'],['phase','위상 절연체','정밀 회피 보상 강화','회피','signal'],['glass','유리 회로','치명타 피해 증가, 피격 시 고장','결함','signal'],['parasite','기생 배터리','적 처치 시 전력 임시 증가','처치','power'],['igniter','수동 점화기','화상 적 폭발 강화','화염','power'],['cryo','극저온 캡슐','동결 파쇄 피해 증가','냉기','cool'],['cable','전도성 케이블','감전 연쇄 범위 증가','전기','signal'],['cloner','결함 복제기','낮은 확률로 효과 재발동','복제','signal']];
const shapes=[[[0,0]],[[0,0],[1,0]],[[0,0],[0,1]],[[0,0],[1,0],[0,1]],[[0,0],[1,0],[2,0]],[[0,0],[1,0],[0,1],[1,1]]];
const modules=[];moduleBase.forEach((x,i)=>modules.push({id:x[0],name:x[1],desc:x[2],tags:[x[3]],connector:x[4],shape:shapes[i%6],rarity:['common','uncommon','rare','epic'][i%4],power:1+i%3,weight:1+(i+1)%3}));
[['mk2','개량형','효과 12% 강화'],['compact','소형','공간 효율 증가'],['overclock','과급형','효과 강화, 전력 증가']].forEach((f,fi)=>moduleBase.slice(0,fi===2?14:13).forEach((x,i)=>modules.push({id:`${x[0]}_${f[0]}`,name:`${f[1]} ${x[1]}`,desc:`${x[2]}. ${f[2]}`,tags:[x[3],f[1]],connector:x[4],shape:shapes[(i+fi+2)%6],rarity:['uncommon','rare','epic'][fi],power:2+fi,weight:1+(i+fi)%3})));
modules.length=60;
const activeData=[['repair','탄환 소거기','주변 적 탄환 제거'],['repair_drone','수리 드론','생명력 또는 방어판 회복'],['airstrike','유도 폭격기','표적 지역 폭격'],['slow','시간 감속 장치','적과 적 탄환 감속'],['gravity','중력 우물','적과 탄환을 한 지점으로 끌어당김'],['blink','비상 순간이동기','조준 방향으로 순간이동'],['ammo_synth','탄약 합성기','예비 탄약 생성'],['decoy','홀로그램 미끼','적의 목표를 유인'],['overload','과부하 스위치','짧은 시간 공격력·연사 증가'],['turret','휴대용 포탑','자동 사격 포탑 설치'],['tactical_reload','전술 재장전','즉시 재장전 및 무료 탄창'],['mutation','강제 변이','주변 적에게 상태 이상 2종'],['reroll','가격 조작','현재 보상 재생성'],['hack','권한 탈취','기계 적을 잠시 아군화'],['barrier','전개 방벽','탄환을 막는 방벽 생성'],['minefield','자기 지뢰망','주변에 추적 지뢰 설치'],['clone_drone','복제 드론','현재 무기를 모방하는 드론'],['nanite','나노 수복장','지속 회복 영역'],['phase_bomb','위상 폭탄','적 탄환을 되돌리는 폭발'],['core_burst','심장 코어 방출','모든 자원을 소비한 대폭발']];
const actives=activeData.map((x,i)=>({id:x[0],name:x[1],desc:x[2],cooldown:12+i%5*3}));
const areas=[['scrap','폐기 조립라인','#b97842',['컨베이어','프레스','가스통','용접 레이저','파괴 기계']],['bio','생화학 처리시설','#6dbf62',['독성 웅덩이','증기 분출','점화 가스','부식 바닥','화학 장치']],['ammo','중앙 탄약저장고','#d55445',['탄약 상자','자동 포탑','경보 레이저','방폭문','반사벽']],['command','지휘 제어망','#8d6bd8',['이동 벽','순간이동 타일','탄속 영역','중력 변화','삭제 구역']],['memory','기억 보관소','#d9c7ff',['기억 재현','선택 전투','인격 데이터','과거 기록','진실 엔딩']]].map(x=>({id:x[0],name:x[1],color:x[2],gimmicks:x[3]}));
const enemyNames=[['스크랩 러너','볼트 슈터','캐리어','프레스 핸드','실드 워커','용접 비틀','폐기 드론','조립 감독관'],['스포어 팟','리치 호퍼','산성 사수','배양체','신경 벌레','가스 벨로우','실험 간호기','변이 경비병'],['마크스맨','그레네디어','탄약 노예기','방폭병','추적 지뢰','미사일 드론','포대 운반차','탄도 분석기'],['커서','방화벽','복제 프로세스','오류 사냥꾼','데이터 스나이퍼','지연 노드','권한 관리자','삭제 프로토콜']];
const behaviors=['chase','burst','summon','telegraph','shield','laser','fan','support'];const enemies=[];enemyNames.forEach((ns,z)=>ns.forEach((n,k)=>enemies.push({id:`e${z}_${k}`,name:n,zone:z,behavior:behaviors[k],hp:38+z*22+k*7,speed:70+k*17%55+z*5,damage:8+z*3+k%4,color:areas[z].color,r:14+k%3*3})));
const elites=[['과충전형','이동·공격 속도 증가'],['장갑형','전방 방어 강화'],['복제형','분신 생성'],['폭발형','사망 폭발'],['흡혈형','피해량 일부 회복'],['위상형','주기적 무적'],['거대형','체력·크기 증가'],['광폭형','저체력 공격 강화'],['저주형','저주 탄환'],['공명형','동일 공격 저항'],['소환형','지원 적 생성'],['결함형','불규칙 고위험 패턴']].map((x,i)=>({id:`elite${i}`,name:x[0],desc:x[1],hp:1.65+i%3*.25,speed:1.05+i%4*.08,damage:1.2+i%3*.15}));
const minibosses=[['foreman','폐기장 감독기',0,900,'#e59a58'],['chimera','배양 키메라',1,1200,'#77db72'],['siege','공성 포대 OX-4',2,1500,'#e15f50'],['rootkit','루트킷 관리자',3,1800,'#a47cea']].map(x=>({id:x[0],name:x[1],zone:x[2],hp:x[3],color:x[4]}));
const bosses=[['gr01','폐기물 압축기 GR-01',0,2400,'#d38a4c',['벽 압축과 파편','회전 프레스와 톱날','안전 구역과 코어 노출']],['eve09','누출된 실험체 EVE-09',1,3100,'#76d56e',['독성 탄막과 도약','적·청 개체 분열','상태 적응과 복합 탄막']],['atlas','자동포대 열차 ATLAS',2,3900,'#db5a4d',['기관총·미사일·지뢰','3개 차량 분리','중앙 코어와 회전 레이저']],['motherline','MOTHERLINE',3,5200,'#a17aec',['분석과 스캔','플레이어 빌드 모방','코어 노드 최적화','종료 명령과 선택']],['memory_dev','최초 개발자 기억 개체',4,4300,'#d9c7ff',['기억 패턴 재현','선택 기반 공격','인격 분리 판정']]].map(x=>({id:x[0],name:x[1],zone:x[2],hp:x[3],color:x[4],phases:x[5]}));
const roomKinds=['combat','combat','combat','elite','reward','shop','craft','medical','event','challenge','secret','boss'];const rooms=[];for(let i=0;i<120;i++){const z=Math.floor(i/24)%5,k=roomKinds[i%12],obs=[];for(let j=0;j<3+i%6;j++)obs.push({x:120+(i*97+j*173)%1040,y:100+(i*53+j*131)%520,w:38+(i+j)%4*28,h:34+(i+j*2)%3*30});rooms.push({id:`room_${String(i).padStart(3,'0')}`,zone:z,kind:k,name:`${areas[z].name} ${k.toUpperCase()}-${i%24+1}`,obstacles:obs,hazard:i%5,waves:2+i%3})}
const eventTitles=['봉쇄된 작업반','불량품 경매','고장 난 의무기','MOTHERLINE의 질문','잊힌 휴게실','무인 자판기','밀수상 통신','죽은 회수자의 가방','기억 조각','금지된 설계도','부식된 금고','통제권 거래','고장 난 복제기','위험한 과충전','기계의 장례','살아 있는 배양조','탄약 도박','불법 수리소','자동 계약서','사라진 작업자','허브 구조 신호','공장 아이의 음성','결함 코어','보안 우회','생산량 투표','퇴역 병기','기억 삭제실','폐쇄 회로','고철 숭배자','거짓 출구','MOTHERLINE 백업','검은 시장 배송','최초 명령','회수자 명단','심장 코어 공명'];
const events=eventTitles.map((n,i)=>({id:`event${i}`,name:n,text:`${n}에서 위험과 보상을 선택한다.`,choices:[{label:'안전한 선택',effect:'heal',value:12+i%8},{label:'위험 감수',effect:'loot',value:1+i%3},{label:'저주 계약',effect:'curse',value:1}]}));
const tags=['화염','냉기','전기','부식','출혈','공허','충격','보호막','정밀','복제','처치','회수','탄약','중량','회피','결함','폭발','도탄','유도','신호'];
const synergies=[['steam','증기 폭발',['화염','냉기'],'화상과 냉기가 만나 범위 폭발'],['circuit','폐쇄 회로',['전기','신호'],'감전 연쇄가 보호막 생성'],['last','마지막 한 발',['폭발','탄약'],'마지막 탄환 피해와 폭발 강화'],['mirror','거울 탄도',['도탄','복제'],'도탄 시 복제 탄환 생성'],['hunter','사냥꾼의 공명',['정밀','보스'],'동일 대상 연속 명중 강화']].map(x=>({id:x[0],name:x[1],tags:x[2],desc:x[3]}));for(let i=0;i<45;i++){let a=tags[i%20],b=tags[(i*7+3)%20];if(a===b)b=tags[(i*7+4)%20];synergies.push({id:`syn${i}`,name:`${a} × ${b} 프로토콜`,tags:[a,b],desc:`${a} 효과와 ${b} 효과가 결합되어 전투 성능이 변화한다.`})}
const achNames=['첫 회수','첫 보스 격파','공장 심층 진입','MOTHERLINE 정지','진실 확인','거래 성립','고저주 생존','완벽 재장전 20회','정밀 회피 50회','무피격 방 클리어','무피격 보스','10연속 처치','1000체 처치','모든 프레임 사용','모든 총열 발견','모든 탄창 발견','모든 코어 발견','모듈 수집가','액티브 전문가','시너지 첫 발견','시너지 10종','시너지 50종','과부하 완주','무과부하 완주','기본 무기 완주','저체력 보스 격파','탄환 반사 처치','상태 이상 4종','상점 파산','고철 부자','비밀방 발견','기억 보관소 진입','셸-07 해금','위협 5 완료','위협 10 완료','사용자 계약 3개','빠른 모드 완료','무한 공장 20층','보스 연속전 완료','일일 시드 완료','모든 캐릭터 완료','모든 엔딩','도감 50%','도감 100%','LAST MAGAZINE'];const achievements=achNames.map((n,i)=>({id:`ach${i}`,name:n,desc:`${n} 조건을 달성한다.`,hidden:[4,6,31,32,44].includes(i)}));
const contracts=[['death_bullets','사망 탄환','모든 적이 사망 시 탄환 발사',1.15],['low_heal','회복 부족','회복량 50% 감소',1.12],['elite_rise','엘리트 증식','엘리트 등장 확률 증가',1.2],['small_bag','협소한 가방','가방 하단 6칸 봉쇄',1.18],['frame_lock','프레임 고정','런 중 무기 프레임 교체 불가',1.1],['time_limit','생산 마감','방 전투 제한 시간',1.2],['boss_regen','자가 수복','보스가 단계 전환 시 회복',1.25]].map(x=>({id:x[0],name:x[1],desc:x[2],mult:x[3]}));
const modes=[['standard','표준 모드','4개 구역과 최종 보스. 구역당 9개 방.',9],['quick','빠른 모드','압축 보상과 구역당 5개 방.',5],['endless','무한 공장','구역이 반복되며 위협이 계속 상승.',7,1],['bossrush','보스 연속전','발견한 주요 보스를 연속 상대.',1,1],['training','훈련장','무기·부품·적·보스 패턴 자유 시험.',1]].map(x=>({id:x[0],name:x[1],desc:x[2],rooms:x[3],locked:!!x[4]}));
const endings=[['basic','기본 엔딩','MOTHERLINE 중앙 코어를 파괴한다.'],['trade','거래 엔딩','공장 통제권을 밀수 세력에 판매한다.'],['truth','진실 엔딩','기억 보관소의 기원을 확인하고 중앙 인격을 결정한다.'],['curse','고저주 엔딩','높은 저주 상태에서 공장의 새로운 규칙이 된다.']].map(x=>({id:x[0],name:x[1],desc:x[2]}));
window.LM_DATA={version:'1.0-web-complete',characters:chars,weapons:w,barrels:B,magazines:M,cores:C,modules,actives,areas,enemies,elites,minibosses,bosses,rooms,events,synergies,achievements,contracts,modes,endings};
})();
