function meleeAttack(s){const p=run.player,ang=Math.atan2(p.aimY,p.aimX);for(const e of run.enemies){const d=dist(p,e),a=Math.atan2(e.y-p.y,e.x-p.x);if(d<170&&Math.abs(angleDiff(a,ang))<1.05)damageEnemy(e,s.damage,true)}for(let i=run.enemyBullets.length-1;i>=0;i--){const b=run.enemyBullets[i];if(dist(p,b)<125){b.team='player';b.vx*=-1.3;b.vy*=-1.3;run.bullets.push(b);run.enemyBullets.splice(i,1)}}run.camera.shake=7}
function angleDiff(a,b){return Math.atan2(Math.sin(a-b),Math.cos(a-b))}
function statusColor(s){return {burn:'#ff7a45',freeze:'#7de8ff',shock:'#ffe26b',corrode:'#88e85f',bleed:'#d94b68',void:'#b68cff',impact:'#fff2bc',absorb:'#79fff2',photon:'#fff',clone:'#c5a5ff',devour:'#ffbd75',return:'#9ff'}[s]||'#91f3ff'}
function applyStatus(e,s){if(!s)return;e.statuses[s]=(e.statuses[s]||0)+1;const max={burn:5,freeze:5,shock:5,corrode:5,bleed:5}[s]||3;e.statuses[s]=Math.min(max,e.statuses[s]);if(s==='freeze'&&e.statuses[s]>=5&&!e.boss)e.frozen=1.2;if(run.character.id==='nova'&&Object.keys(e.statuses).filter(k=>e.statuses[k]>0).length>=2&&(!e.mutationCd||e.mutationCd<=0)){e.mutationCd=1.2;damageEnemy(e,35,true);burst(e.x,e.y,'#b8fffa',12)}}
function damageEnemy(e,amount,strong=false,b=null){if(e.dead||e.inv>0)return 0;if(e.shield>0){const d=Math.min(e.shield,amount);e.shield-=d;amount-=d;if(amount<=0)return d}if(e.statuses.corrode)amount*=1+e.statuses.corrode*.06;if(e.statuses.freeze)amount*=1+e.statuses.freeze*.025;if(e.boss)amount*=effectiveStats().bossDamage||1;e.hp-=amount;run.damage+=amount;save.stats.damage+=amount;e.hit=.08;if(save.settings.damageNumbers)run.texts.push({x:e.x,y:e.y-20,t:.65,text:`${Math.round(amount)}${b?.crit?'!':''}`,color:b?.crit?'#ffe36e':'#fff'});if(strong)run.camera.shake=Math.max(run.camera.shake,4);if(e.hp<=0)killEnemy(e,b);return amount}
function killEnemy(e,b){if(e.dead)return;e.dead=true;run.kills++;save.stats.kills++;run.player.focus=Math.min(8,run.player.focus+1);burst(e.x,e.y,e.color||'#ff647b',e.boss?40:12);if(e.boss){achievement(`ach${Math.min(4,run.zone+1)}`);roomComplete(true)}else{if(run.weapon.magazine.id==='regen'&&rand()<.16)run.player.ammo=Math.min(effectiveStats().mag,run.player.ammo+1);if(effectiveStats().devour)run.devourBuff=Math.min(5,(run.devourBuff||0)+1);if(run.contracts.includes('death_bullets'))radialShots(e.x,e.y,6,150,8,'enemy');if(rand()<.28)run.pickups.push({kind:rand()<.78?'scrap':'heal',x:e.x,y:e.y,r:7,t:20,value:rand()<.78?2+Math.floor(rand()*5):3})}unlockCodex('enemies',e.id);if(run.kills===1)achievement('ach0');if(run.kills>=1000)achievement('ach12')}
function hurtPlayer(amount,source='enemy'){const p=run.player;if(p.inv>0||run.over)return;run.noHitRoom=false;p.focus=0;let left=amount;if(p.tempShield>0){const d=Math.min(p.tempShield,left);p.tempShield-=d;left-=d}if(left>0&&p.shield>0){const d=Math.min(p.shield,left);p.shield-=d;left-=d}if(left>0)p.hp-=left;p.inv=.75;p.hitFlash=.2;run.camera.shake=10;burst(p.x,p.y,'#ff4b67',18);run.lastDamageSource=source;tone(80,.15,'sawtooth',.05);if(p.hp<=0)endRun(false)}
function radialShots(x,y,count,speed,damage,team='enemy',offset=0){for(let i=0;i<count;i++){const a=offset+i/count*TAU;const b={x,y,px:x,py:y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:5,life:5,damage,team,color:team==='enemy'?'#ff627e':'#83f2ff'};(team==='enemy'?run.enemyBullets:run.bullets).push(b)}}
function aimedShot(e,speed=240,damage=e.damage,count=1,spread=.18){const target=run.decoy||run.player,a=Math.atan2(target.y-e.y,target.x-e.x);for(let i=0;i<count;i++){const ang=a+(i-(count-1)/2)*spread;run.enemyBullets.push({x:e.x,y:e.y,px:e.x,py:e.y,vx:Math.cos(ang)*speed,vy:Math.sin(ang)*speed,r:5,life:5,damage,team:'enemy',color:'#ff657f'})}}
function burst(x,y,color,count=8){for(let i=0;i<count;i++){const a=rand()*TAU,s=35+rand()*170;run.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,r:2+rand()*4,t:.25+rand()*.45,max:.7,color})}}
function update(dt){if(!run||run.paused||run.over||screen!=='game')return;dt=Math.min(dt,.033);run.elapsed+=dt;const p=run.player,s=effectiveStats();p.inv=Math.max(0,p.inv-dt);p.hitFlash=Math.max(0,p.hitFlash-dt);p.fireCd=Math.max(0,p.fireCd-dt);p.rollCd=Math.max(0,p.rollCd-dt);p.activeCd=Math.max(0,p.activeCd-dt);p.overheated=Math.max(0,p.overheated-dt);p.heat=Math.max(0,p.heat-dt*(p.overheated?18:10));p.focus=Math.max(0,p.focus-dt*.22);if(run.slowTime)run.slowTime=Math.max(0,run.slowTime-dt);if(run.gravityTime)run.gravityTime=Math.max(0,run.gravityTime-dt);if(run.overload)run.overload=Math.max(0,run.overload-dt);if(run.freeAmmo)run.freeAmmo=Math.max(0,run.freeAmmo-dt);
 const move=inputMove(),aim=inputAim();if(aim.x||aim.y){p.aimX=aim.x;p.aimY=aim.y}
 if(p.roll>0){p.roll-=dt;const mult=860*(s.rollDistance||1);p.x+=p.rollDir.x*mult*dt;p.y+=p.rollDir.y*mult*dt;if(p.roll<.18)p.inv=Math.max(p.inv,.08)}else{const targetV={x:move.x*p.speed*s.moveMult,y:move.y*p.speed*s.moveMult};p.vx=lerp(p.vx,targetV.x,1-Math.pow(.02,dt/.08));p.vy=lerp(p.vy,targetV.y,1-Math.pow(.02,dt/.08));p.x+=p.vx*dt;p.y+=p.vy*dt}
 collideWorld(p);if(p.reloading){p.reloadT+=dt*(p.reloadPerfect?4:1);if(p.reloadT>=s.reload)finishReload()}else if(isFiring())fire();
 updateBullets(dt);updateEnemies(dt);updatePickups(dt);updateEffects(dt);updateGimmicks(dt);if(run.turret)updateTurret(dt);if(run.cloneDrone)updateCloneDrone(dt);if(run.nanite){run.nanite.t-=dt;if(dist(p,run.nanite)<90)p.hp=Math.min(p.maxHp,p.hp+4*dt);if(run.nanite.t<=0)run.nanite=null}if(run.decoy&&(run.decoy.t-=dt)<=0)run.decoy=null;if(run.barrier&&(run.barrier.t-=dt)<=0)run.barrier=null;
 if(!run.roomClear&&!run.enemies.some(e=>!e.dead)){if(run.wave<run.waves){if(!run.pendingWave){run.pendingWave=true;setTimeout(()=>{if(run&&!run.roomClear)spawnWave()},450)}}else roomComplete(false)}updateHUD()}