'use strict';
function inputMove(){let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),y=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);if(Math.abs(touch.move.x)+Math.abs(touch.move.y)>.05){x=touch.move.x;y=touch.move.y}return norm(x,y)}
function inputAim(){let a={x:touch.aim.x,y:touch.aim.y};if(Math.abs(a.x)+Math.abs(a.y)<.08&&matchMedia('(pointer:fine)').matches){a=norm(mouse.x-run.player.x,mouse.y-run.player.y)}if(Math.abs(a.x)+Math.abs(a.y)<.08&&save.settings.aimAssist>0){const t=nearestEnemy();if(t)a=norm(t.x-run.player.x,t.y-run.player.y)}return a}
function isFiring(){return mouse.down||Math.abs(touch.aim.x)+Math.abs(touch.aim.y)>.15||keys.has('KeyJ')||keys.has('Enter')}
function nearestEnemy(){let best=null,bd=1e9;for(const e of run.enemies){if(e.dead)continue;const d=(e.x-run.player.x)**2+(e.y-run.player.y)**2;if(d<bd){bd=d;best=e}}return best}
function startReload(){const p=run.player,s=effectiveStats();if(p.reloading||p.ammo>=s.mag||p.reserve<=0)return;p.reloading=true;p.reloadT=0;p.reloadPerfect=false;$('#reloadText').textContent='RELOADING';tone(260,.05,'square',.025)}
function reloadPress(){const p=run?.player;if(!p)return;if(!p.reloading){startReload();return}const s=effectiveStats(),progress=p.reloadT/s.reload;if(progress>.55&&progress<.76&&!p.reloadPerfect){p.reloadPerfect=true;p.reloadT=s.reload*.9;run.perfectReloads++;toast('PERFECT RELOAD');tone(880,.1,'triangle',.04);if(run.weapon.frame.id==='pistol')p.perfectCrit=true;if(run.weapon.magazine.id==='magnetic'){const removed=Math.min(12,run.enemyBullets.length);run.enemyBullets.splice(0,removed);p.tempShield+=removed*1.5}}}
function finishReload(){const p=run.player,s=effectiveStats(),need=s.mag-p.ammo,take=Math.min(need,p.reserve);p.ammo+=take;p.reserve-=take;p.reloading=false;p.reloadT=0;if(run.weapon.magazine.id==='freeReload'&&rand()<.2)p.reserve+=take;if(p.perfectReload&&run.weapon.frame.id==='pistol')p.perfectCrit=true;tone(440,.06,'square',.03)}
function dash(){if(!run||run.paused||run.over)return;const p=run.player;if(p.rollCd>0||p.roll>0)return;let d=inputMove();if(!d.x&&!d.y)d={x:p.aimX,y:p.aimY};p.roll=.52;p.rollCd=.87;p.rollDir=d;p.inv=.34;p.reloading=false;p.reloadT=0;run.camera.shake=5;tone(140,.09,'sawtooth',.04)}
function activate(){if(!run||run.player.activeCd>0)return;const p=run.player,a=run.active;p.activeCd=a.cooldown;toast(a.name);tone(520,.12,'triangle',.045);switch(a.id){case'repair':run.enemyBullets=[];p.tempShield+=20;break;case'repair_drone':p.hp=Math.min(p.maxHp,p.hp+30);break;case'airstrike':for(const e of run.enemies)damageEnemy(e,95,true);break;case'slow':run.slowTime=5;break;case'gravity':run.gravityTime=5;break;case'blink':p.x=clamp(p.x+p.aimX*220,40,W-40);p.y=clamp(p.y+p.aimY*220,40,H-40);p.inv=.5;break;case'ammo_synth':p.reserve+=effectiveStats().mag*2;break;case'decoy':run.decoy={x:p.x,y:p.y,t:6};break;case'overload':run.overload=6;break;case'turret':run.turret={x:p.x,y:p.y,t:12,cd:0};break;case'tactical_reload':p.reserve+=effectiveStats().mag;finishReload();run.freeAmmo=6;break;case'mutation':for(const e of run.enemies){applyStatus(e,pick(['burn','freeze','shock','corrode','bleed']));applyStatus(e,pick(['burn','freeze','shock','corrode','bleed']))}break;case'reroll':run.shopRerolls++;break;case'hack':for(const e of run.enemies.filter(x=>!x.boss).slice(0,3))e.hacked=5;break;case'barrier':run.barrier={x:p.x+p.aimX*80,y:p.y+p.aimY*80,t:8};break;case'minefield':for(let i=0;i<8;i++)run.pickups.push({kind:'mine',x:p.x+Math.cos(i/8*TAU)*100,y:p.y+Math.sin(i/8*TAU)*100,r:10,t:12});break;case'clone_drone':run.cloneDrone={t:10,cd:0};break;case'nanite':run.nanite={x:p.x,y:p.y,t:8};break;case'phase_bomb':for(const b of run.enemyBullets){b.team='player';b.vx*=-1;b.vy*=-1;run.bullets.push(b)}run.enemyBullets=[];break;case'core_burst':for(const e of run.enemies)damageEnemy(e,250,true);p.hp=Math.max(1,p.hp-25);p.shield=0;break;default:p.tempShield+=15}}
function fire(){const p=run.player,s=effectiveStats();if(p.reloading||p.overheated>0||p.fireCd>0||p.ammo<s.ammoUse)return;if(s.misfire&&rand()<s.misfire){p.fireCd=.22;toast('발사 실패');tone(65,.08,'square',.02);return}p.ammo-=s.ammoUse;p.fireCd=s.rate*(run.overload?0.65:1);p.heat+=s.heatPer;if(p.heat>=100){p.overheated=1.8;p.heat=100;toast('OVERHEAT');tone(90,.2,'sawtooth',.05)}let aim={x:p.aimX,y:p.aimY};if(save.settings.aimAssist>0){const t=nearestEnemy();if(t){const ta=norm(t.x-p.x,t.y-p.y);aim=norm(lerp(aim.x,ta.x,save.settings.aimAssist*.22),lerp(aim.y,ta.y,save.settings.aimAssist*.22))}}const base=Math.atan2(aim.y,aim.x);let shots=s.projectiles;if(run.weapon.frame.kind==='burst')shots=3;if(run.weapon.frame.kind==='drone')shots=2;if(run.weapon.frame.kind==='melee'){meleeAttack(s);return}if(run.weapon.frame.kind==='beam')shots=1;for(let i=0;i<shots;i++){const spread=(i-(shots-1)/2)*s.spread+(rand()-.5)*s.spread*.35,ang=base+spread;createBullet(p.x+Math.cos(ang)*22,p.y+Math.sin(ang)*22,ang,s)}if(run.weapon.frame.kind==='grenade')run.camera.shake=6;if(run.weapon.frame.id==='shotgun')run.camera.shake=5;tone(180+rand()*80,.04,run.weapon.frame.kind==='beam'?'sawtooth':'square',.025);if(p.ammo<=0&&save.settings.autoReload)setTimeout(()=>run&&!run.over&&startReload(),90)}
function createBullet(x,y,ang,s,scale=1){let dmg=s.damage*scale;if(s.unstable)dmg*=.7+rand()*.9;let crit=run.player.perfectCrit||rand()<s.crit;run.player.perfectCrit=false;if(crit)dmg*=s.critDamage;const b={x,y,px:x,py:y,vx:Math.cos(ang)*s.bulletSpeed,vy:Math.sin(ang)*s.bulletSpeed,r:5*s.size,life:1.4*s.range,damage:dmg,team:'player',pierce:s.pierce,bounce:s.bounce,explosion:s.explosion,homing:s.homing,status:s.status,crit,split:s.split||0,returning:s.returning||0,clone:s.clone||0,color:statusColor(s.status)};run.bullets.push(b)}