'use strict';
const D=window.LM_DATA;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false});
const W=1280,H=720,TAU=Math.PI*2;
let DPR=1,last=performance.now(),raf=0,screen='title',selectedChar='mara',selectedMode='standard',selectedThreat=0,selectedContracts=new Set();
let save=loadSave(),run=null,audio=null,keys=new Set(),mouse={x:W/2,y:H/2,down:false},touch={move:{id:null,x:0,y:0},aim:{id:null,x:0,y:0}},uiBusy=false;
const screens={title:$('#titleScreen'),setup:$('#setupScreen'),overlay:$('#overlayScreen'),reward:$('#rewardScreen'),route:$('#routeScreen'),inventory:$('#inventoryScreen')};
const hud=$('#hud'),mobile=$('#mobileControls'),toastEl=$('#toast');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const norm=(x,y)=>{const l=Math.hypot(x,y);return l?{x:x/l,y:y/l}:{x:0,y:0}};
const pick=a=>a[Math.floor(rand()*a.length)];
function seedHash(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
let rngState=1;function setSeed(s){rngState=seedHash(String(s))||1}function rand(){rngState^=rngState<<13;rngState^=rngState>>>17;rngState^=rngState<<5;return (rngState>>>0)/4294967296}
function resize(){DPR=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*DPR);canvas.height=Math.round(innerHeight*DPR);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}
addEventListener('resize',resize,{passive:true});resize();
function loadSave(){try{return Object.assign({version:1,core:0,memory:0,blueprints:[],unlocks:['mara','kane','nova','rex'],modes:['standard','quick','training'],codex:{weapons:[],parts:[],modules:[],enemies:[],bosses:[],events:[],synergies:[]},achievements:[],endings:[],stats:{runs:0,wins:0,kills:0,damage:0,bestThreat:0,bestEndless:0},settings:{sound:true,screenShake:1,aimAssist:.65,damageNumbers:true,flash:.7,autoReload:true,colorMode:'normal',uiScale:1}},JSON.parse(localStorage.getItem('lastMagazineSave')||'{}'))}catch(e){return {version:1,core:0,memory:0,blueprints:[],unlocks:['mara','kane','nova','rex'],modes:['standard','quick','training'],codex:{weapons:[],parts:[],modules:[],enemies:[],bosses:[],events:[],synergies:[]},achievements:[],endings:[],stats:{runs:0,wins:0,kills:0,damage:0,bestThreat:0,bestEndless:0},settings:{sound:true,screenShake:1,aimAssist:.65,damageNumbers:true,flash:.7,autoReload:true,colorMode:'normal',uiScale:1}}}}
function store(){localStorage.setItem('lastMagazineSave',JSON.stringify(save));updateSaveSummary()}
function unlockCodex(type,id){const arr=save.codex[type]||(save.codex[type]=[]);if(!arr.includes(id)){arr.push(id);store()}}
function achievement(id){if(!save.achievements.includes(id)){save.achievements.push(id);const a=D.achievements.find(x=>x.id===id);toast(`업적 달성: ${a?.name||id}`);store()}}
function toast(msg,ms=1800){toastEl.innerHTML=msg;toastEl.classList.add('show');clearTimeout(toastEl._t);toastEl._t=setTimeout(()=>toastEl.classList.remove('show'),ms)}
function ensureAudio(){if(audio)return;audio=new (window.AudioContext||window.webkitAudioContext)()}
function tone(freq=.2,dur=.06,type='square',vol=.03){if(!save.settings.sound)return;ensureAudio();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function show(name){Object.values(screens).forEach(x=>x.classList.remove('active'));if(name&&screens[name])screens[name].classList.add('active');screen=name||'game';const inGame=screen==='game';hud.classList.toggle('hidden',!inGame);mobile.classList.toggle('hidden',!inGame);$('#pauseBtn').classList.toggle('hidden',!inGame);$('#mapBtn').classList.toggle('hidden',!inGame);$('#bagBtn').classList.toggle('hidden',!inGame)}
function updateSaveSummary(){$('#saveSummary').textContent=`런 ${save.stats.runs} · 승리 ${save.stats.wins} · 코어 파편 ${save.core} · 도감 ${codexPercent()}%`}
function codexPercent(){const total=D.weapons.length+D.barrels.length+D.magazines.length+D.cores.length+D.modules.length+D.enemies.length+D.bosses.length+D.events.length+D.synergies.length;const got=Object.values(save.codex).reduce((a,b)=>a+(b?.length||0),0);return Math.min(100,Math.round(got/total*100))}
function setupUI(){
 updateSaveSummary();
 $('#characterList').innerHTML=D.characters.map(c=>`<button class="card ${selectedChar===c.id?'selected':''} ${save.unlocks.includes(c.id)?'':'locked'}" data-char="${c.id}"><span class="tag">${save.unlocks.includes(c.id)?'READY':'LOCKED'}</span><h4>${c.name}</h4><p>${c.role}</p><p>HP ${c.hp} · 속도 ${Math.round(c.speed*100)}% · 방어판 ${c.shield}</p></button>`).join('');
 $('#modeList').innerHTML=D.modes.map(m=>`<button class="card ${selectedMode===m.id?'selected':''} ${save.modes.includes(m.id)?'':'locked'}" data-mode="${m.id}"><span class="tag">${save.modes.includes(m.id)?'READY':'LOCKED'}</span><h4>${m.name}</h4><p>${m.desc}</p></button>`).join('');
 $('#contractList').innerHTML=D.contracts.map(c=>`<label class="contract"><input type="checkbox" data-contract="${c.id}" ${selectedContracts.has(c.id)?'checked':''}><span><b>${c.name}</b><br><small>${c.desc} · 점수 ×${c.mult}</small></span></label>`).join('');
 updateSetupSummary();
}
function updateSetupSummary(){const c=D.characters.find(x=>x.id===selectedChar),m=D.modes.find(x=>x.id===selectedMode);let mult=(1+selectedThreat*.1);selectedContracts.forEach(id=>mult*=D.contracts.find(x=>x.id===id).mult);$('#setupSummary').innerHTML=`<b>${c.name}</b> · ${m.name} · 위협 ${selectedThreat}<br><small>예상 점수 배율 ×${mult.toFixed(2)}</small>`}
$('#startSetupBtn').onclick=()=>{setupUI();show('setup')};
$('[data-back]')?.addEventListener('click',()=>show('title'));
$('#threatRange').oninput=e=>{selectedThreat=+e.target.value;$('#threatValue').textContent=selectedThreat;updateSetupSummary()};
$('#characterList').onclick=e=>{const b=e.target.closest('[data-char]');if(!b)return;if(!save.unlocks.includes(b.dataset.char)){toast('해금 조건이 필요합니다.');return}selectedChar=b.dataset.char;setupUI()};
$('#modeList').onclick=e=>{const b=e.target.closest('[data-mode]');if(!b)return;if(!save.modes.includes(b.dataset.mode)){toast('기본 엔딩 후 해금됩니다.');return}selectedMode=b.dataset.mode;setupUI()};
$('#contractList').onchange=e=>{const id=e.target.dataset.contract;if(!id)return;e.target.checked?selectedContracts.add(id):selectedContracts.delete(id);updateSetupSummary()};
$('#launchBtn').onclick=()=>startRun();
$$('[data-open]').forEach(b=>b.onclick=()=>openMeta(b.dataset.open));
function openMeta(type){
 const modal=$('#overlayModal');
 if(type==='codex')renderCodex(modal);else if(type==='achievements')renderAchievements(modal);else if(type==='settings')renderSettings(modal);else modal.innerHTML=`<header><div><p class="eyebrow">BUILD INFORMATION</p><h2>LAST MAGAZINE</h2></div><button class="close" data-close>×</button></header><p>GDD 1.0 전체 콘텐츠를 데이터로 포함한 모바일 웹 플레이 빌드.</p><table class="list-table"><tr><th>버전</th><td>${D.version}</td></tr><tr><th>엔진</th><td>HTML5 Canvas 프로토타입</td></tr><tr><th>정식 목표</th><td>Godot 4.x / Steam</td></tr><tr><th>저장</th><td>브라우저 LocalStorage</td></tr></table>`;
 modal.querySelector('[data-close]').onclick=()=>show(run?'game':'title');show('overlay')
}
function renderCodex(modal){const tabs=[['weapons','무기'],['parts','부품'],['modules','모듈'],['enemies','적'],['bosses','보스'],['events','이벤트'],['synergies','시너지']];modal.innerHTML=`<header><div><p class="eyebrow">ARCHIVE</p><h2>도감 ${codexPercent()}%</h2></div><button class="close" data-close>×</button></header><div class="tabs">${tabs.map((t,i)=>`<button data-tab="${t[0]}" class="${i?'':'active'}">${t[1]}</button>`).join('')}</div><div id="codexBody" class="scroll-list"></div>`;const draw=t=>{let list=[];if(t==='weapons')list=D.weapons;if(t==='parts')list=[...D.barrels,...D.magazines,...D.cores];else if(t==='modules')list=D.modules;else if(t==='enemies')list=D.enemies;else if(t==='bosses')list=D.bosses;else if(t==='events')list=D.events;else if(t==='synergies')list=D.synergies;const got=save.codex[t]||[];$('#codexBody').innerHTML=`<table class="list-table">${list.map(x=>`<tr><td>${got.includes(x.id)?x.name:'???'}</td><td>${got.includes(x.id)?(x.desc||x.role||x.phases?.join(' / ')||x.tags?.join(', ')||'기록 확보'):'미발견'}</td></tr>`).join('')}</table>`};draw('weapons');modal.querySelector('.tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;modal.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.tab)};modal.querySelector('[data-close]').onclick=()=>show(run?'game':'title');show('overlay')}
function renderAchievements(modal){modal.innerHTML=`<header><div><p class="eyebrow">STEAM ACHIEVEMENT MIRROR</p><h2>업적 ${save.achievements.length}/${D.achievements.length}</h2></div><button class="close" data-close>×</button></header><div class="scroll-list">${D.achievements.map(a=>`<div class="achievement ${save.achievements.includes(a.id)?'done':''}"><span><b>${a.hidden&&!save.achievements.includes(a.id)?'비밀 업적':a.name}</b><br><small>${a.hidden&&!save.achievements.includes(a.id)?'조건이 숨겨져 있습니다.':a.desc}</small></span><b>${save.achievements.includes(a.id)?'완료':'미완료'}</b></div>`).join('')}</div>`;modal.querySelector('[data-close]').onclick=()=>show(run?'game':'title');show('overlay')}
function renderSettings(modal){const s=save.settings;modal.innerHTML=`<header><div><p class="eyebrow">ACCESSIBILITY / SETTINGS</p><h2>설정</h2></div><button class="close" data-close>×</button></header><div class="scroll-list"><label class="contract"><input type="checkbox" data-setting="sound" ${s.sound?'checked':''}> 사운드</label><label class="contract"><input type="checkbox" data-setting="autoReload" ${s.autoReload?'checked':''}> 탄창 소진 시 자동 재장전</label><label class="range-row">조준 보정 <b>${Math.round(s.aimAssist*100)}%</b><input type="range" min="0" max="1" step=".05" value="${s.aimAssist}" data-range="aimAssist"></label><label class="range-row">화면 흔들림 <b>${Math.round(s.screenShake*100)}%</b><input type="range" min="0" max="1" step=".1" value="${s.screenShake}" data-range="screenShake"></label><label class="range-row">플래시 강도 <b>${Math.round(s.flash*100)}%</b><input type="range" min="0" max="1" step=".1" value="${s.flash}" data-range="flash"></label><label class="contract"><input type="checkbox" data-setting="damageNumbers" ${s.damageNumbers?'checked':''}> 피해 숫자</label><button id="resetSave">저장 데이터 초기화</button></div>`;modal.onchange=e=>{const k=e.target.dataset.setting;if(k){s[k]=e.target.checked;store()}const r=e.target.dataset.range;if(r){s[r]=+e.target.value;store();renderSettings(modal)}};modal.querySelector('#resetSave').onclick=()=>{if(confirm('모든 저장 데이터를 초기화합니까?')){localStorage.removeItem('lastMagazineSave');location.reload()}};modal.querySelector('[data-close]').onclick=()=>show(run?'game':'title');show('overlay')}
function startRun(){
 ensureAudio();const c=D.characters.find(x=>x.id===selectedChar),m=D.modes.find(x=>x.id===selectedMode);const seed=selectedMode==='daily'?new Date().toISOString().slice(0,10):`${Date.now()}-${Math.random()}`;setSeed(seed);
 const weapon=D.weapons.find(x=>x.id===c.weapon)||D.weapons[0];
 run={seed,mode:m.id,roomsPerZone:m.rooms,zone:0,roomIndex:0,totalRooms:0,routeHistory:[],threat:selectedThreat,contracts:[...selectedContracts],scoreMult:1+selectedThreat*.1,elapsed:0,paused:false,over:false,wave:0,waves:0,room:null,roomClear:false,shopRerolls:0,eventFlags:[],memoryFragments:0,bossKeys:0,curse:0,scrap:c.id==='rex'?110:55,kills:0,damage:0,perfectReloads:0,precisionDodges:0,noHitRoom:true,synergyIds:[],bagExpanded:0,character:c,weapon:{frame:{...weapon},barrel:{...D.barrels[0]},magazine:{...D.magazines[0]},core:{...D.cores[0]}},active:D.actives.find(x=>x.id===c.active)||D.actives[0],modules:[],bag:Array(30).fill(null),bagBlocked:new Set(),player:{x:W/2,y:H/2,r:15,hp:c.hp,maxHp:c.hp,shield:c.shield*20,maxShield:60,tempShield:0,speed:260*c.speed,vx:0,vy:0,aimX:1,aimY:0,roll:0,rollCd:0,inv:0,fireCd:0,reloading:false,reloadT:0,reloadPerfect:false,ammo:weapon.mag,reserve:weapon.mag*12,heat:0,overheated:0,activeCd:0,focus:0,hitFlash:0},enemies:[],bullets:[],enemyBullets:[],particles:[],texts:[],pickups:[],obstacles:[],hazards:[],camera:{shake:0,x:0,y:0},statsCache:null,pendingWave:false,afterBossAction:null,endlessLoop:0};
 run.contracts.forEach(id=>run.scoreMult*=D.contracts.find(x=>x.id===id).mult);
 if(run.contracts.includes('small_bag'))for(let i=24;i<30;i++)run.bagBlocked.add(i);
 unlockCodex('weapons',weapon.id);unlockCodex('parts',run.weapon.barrel.id);unlockCodex('parts',run.weapon.magazine.id);unlockCodex('parts',run.weapon.core.id);
 autoStarterModules();save.stats.runs++;store();achievement('ach0');if(m.id==='bossrush'){run.roomsPerZone=1;loadRoom('boss')}else loadRoom('combat');show('game');tone(150,.16,'sawtooth',.04)
}
function autoStarterModules(){const ids=run.character.id==='nova'?['fan','cable']:run.character.id==='rex'?['shell_collector','magnet']:run.character.id==='kane'?['ballistic','mobile_gen']:['ammo_box','absorber'];ids.forEach((id,k)=>{const m=D.modules.find(x=>x.id===id);if(m){run.modules.push({...m,uid:`m${Date.now()}${k}`,rotation:0,placed:false});unlockCodex('modules',id)}});autoArrangeBag(false)}
function effectiveStats(){
 const f=run.weapon.frame,b=run.weapon.barrel,m=run.weapon.magazine,c=run.weapon.core,p=run.player;let s={damage:f.damage,rate:f.rate,mag:f.mag,reload:f.reload,bulletSpeed:f.speed,projectiles:f.count,spread:f.kind==='spread'?.5:.045,pierce:0,bounce:f.kind==='ricochet'?3:0,explosion:f.kind==='grenade'?72:0,homing:0,size:1,crit:.05,critDamage:1.75,ammoUse:1,heatPer:f.kind==='beam'||f.kind==='spin'?3.2:0,range:1,status:c.status,moveMult:1,power:4,weight:4,maxPower:6,maxWeight:7};
 const apply=e=>{for(const[k,v]of Object.entries(e||{})){if(['damage','rate','mag','reload','bulletSpeed','range','size','ammoUse'].includes(k))s[k]*=v;else if(k==='fireRate')s.rate*=v;else if(k==='projectiles')s.projectiles+=v;else s[k]=(s[k]||0)+v}};apply(b.effects);apply(m.effects);if(c.id==='photon'){s.bulletSpeed*=1.18;s.crit+=.08;s.damage*=.92}if(c.id==='impact')s.damage*=1.05;if(c.id==='void')s.damage*=1.1;if(c.id==='clone')s.clone=.12;if(c.id==='absorb')s.absorb=.018;if(c.id==='devour')s.devour=1;if(c.id==='reverse')s.returning=1;
 const placed=run.modules.filter(x=>x.placed);for(const mod of placed){s.power+=mod.power;s.weight+=mod.weight;for(const t of mod.tags){if(t==='정밀')s.crit+=.025;if(t==='탄약')s.mag*=1.08;if(t==='냉각')s.heatPer*=.86;if(t==='중량')s.moveMult*=1.03;if(t==='결함')s.damage*=1.06;if(t==='보스')s.bossDamage=(s.bossDamage||1)*1.08;if(t==='보호막')s.absorb=(s.absorb||0)+.006;if(t==='회피')s.rollBonus=(s.rollBonus||0)+.04;if(t==='화염'&&c.id==='fire')s.damage*=1.05;if(t==='전기'&&c.id==='electric')s.projectiles+=.08}}
 if(s.power>s.maxPower){const over=s.power-s.maxPower;s.reload*=1+over*.12;s.heatPer*=1+over*.15;s.misfire=Math.min(.28,over*.04)}if(s.weight>s.maxWeight){const over=s.weight-s.maxWeight;s.moveMult*=Math.max(.65,1-over*.055);s.rollDistance=Math.max(.7,1-over*.045)}
 if(run.character.id==='nova')s.statusPower=1.3;if(run.character.id==='kane'){s.rate*=Math.max(.72,1-p.focus*.025);s.reload*=Math.max(.72,1-p.focus*.02)}if(run.character.id==='shell'){s.heatPer*=1.2;s.damage*=1+Math.min(.35,p.heat/300)}
 s.mag=Math.max(1,Math.round(s.mag));s.projectiles=Math.max(1,Math.round(s.projectiles));return s
}
function roomPool(zone,kind){let pool=D.rooms.filter(r=>r.zone===zone&&(kind==='boss'?r.kind==='boss':kind==='elite'?r.kind==='elite':kind==='event'?r.kind==='event':kind==='shop'?r.kind==='shop':kind==='medical'?r.kind==='medical':r.kind==='combat'));if(!pool.length)pool=D.rooms.filter(r=>r.zone===zone);return pool}
function loadRoom(kind='combat'){
 run.roomClear=false;run.noHitRoom=true;run.wave=0;run.pendingWave=false;run.enemies=[];run.bullets=[];run.enemyBullets=[];run.particles=[];run.texts=[];run.pickups=[];const isBoss=kind==='boss';run.room={...pick(roomPool(run.zone,kind)),kind};run.obstacles=run.room.obstacles.map(o=>({...o}));run.hazards=[];run.player.x=W/2;run.player.y=H/2;run.player.vx=run.player.vy=0;run.player.inv=1;run.waves=isBoss?1:run.room.waves;updateHUD();if(isBoss)spawnBoss();else if(kind==='elite'&&run.roomIndex===Math.floor(run.roomsPerZone/2))spawnMiniBoss();else spawnWave();toast(`${D.areas[run.zone].name}<br>${run.room.name}`,1200)
}
function spawnWave(){run.pendingWave=false;run.wave++;const count=3+run.zone*2+run.wave+Math.floor(run.threat/2);for(let i=0;i<count;i++)spawnEnemy();if(run.room.kind==='elite')for(let i=0;i<Math.max(1,Math.floor(count/3));i++){const e=run.enemies[i];if(e)applyElite(e,pick(D.elites))}}
function spawnEnemy(enemyDef=null){const zone=run.zone===4?Math.floor(rand()*4):run.zone;const def=enemyDef||pick(D.enemies.filter(x=>x.zone===zone));const side=Math.floor(rand()*4),pad=70;let x=pad+rand()*(W-pad*2),y=pad+rand()*(H-pad*2);if(side===0)y=80;if(side===1)x=W-80;if(side===2)y=H-80;if(side===3)x=80;const scale=1+run.zone*.25+run.threat*.11+run.totalRooms*.025;const e={...def,x,y,maxHp:def.hp*scale,hp:def.hp*scale,speed:def.speed*(1+run.threat*.025),damage:def.damage*(1+run.threat*.07),cool:.5+rand(),timer:0,phase:0,elite:null,shield:0,inv:0,statuses:{},boss:false,dead:false,angle:rand()*TAU};run.enemies.push(e);unlockCodex('enemies',def.id)}
function applyElite(e,elite){e.elite=elite;e.name=`${elite.name} ${e.name}`;e.maxHp*=elite.hp;e.hp=e.maxHp;e.speed*=elite.speed;e.damage*=elite.damage;e.r*=1.18;if(elite.id==='elite1')e.shield=e.maxHp*.35}
function spawnMiniBoss(){const def=D.minibosses[run.zone%4];const scale=1+run.threat*.1;const e={...def,id:def.id,x:W/2,y:145,r:36,maxHp:def.hp*scale,hp:def.hp*scale,speed:72+run.zone*6,damage:16+run.zone*4,cool:.7,timer:0,phase:1,elite:D.elites[(run.zone*3)%D.elites.length],shield:def.hp*.08,inv:.6,statuses:{},boss:true,miniboss:true,dead:false,angle:0,pattern:0};run.enemies.push(e);run.waves=1;run.wave=1;unlockCodex('bosses',def.id);toast(`MID-BOSS // ${def.name}`,1500)}
function spawnBoss(){const def=run.zone===4?D.bosses[4]:D.bosses[run.zone];const scale=1+run.threat*.12;const e={...def,x:W/2,y:145,r:48,maxHp:def.hp*scale,hp:def.hp*scale,speed:55+run.zone*7,damage:18+run.zone*5+run.threat*1.5,cool:1,timer:0,phase:1,elite:null,shield:0,inv:1,statuses:{},boss:true,dead:false,angle:0,pattern:0};run.enemies.push(e);unlockCodex('bosses',def.id);toast(`BOSS // ${def.name}`,1800);tone(70,.5,'sawtooth',.06)}
