function openShop(){const discount=run.character.id==='rex'?.82:run.character.id==='mara'?.92:1;const items=[makeReward(),makeReward(),makeReward(),makeReward()].filter(x=>!['heal','shield','scrap'].includes(x.type));const m=overlayHTML('불법 부품 상점',`<p>보유 고철: <b>${run.scrap}</b></p><div class="reward-grid">${items.map((r,i)=>{const price=Math.round((45+i*18+run.zone*16)*(r.rarity==='epic'?1.5:1)*discount);r.price=price;return `<button class="reward ${r.rarity}" data-buy="${i}"><span class="type">${r.type} · ${price} 고철</span><h3>${r.name}</h3><p>${r.desc}</p></button>`}).join('')}</div>`,`<button id="shopLeave">나가기</button><button id="shopHeal">수리 25 (${Math.round(35*discount)} 고철)</button>`);m.onclick=e=>{const b=e.target.closest('[data-buy]');if(b){const r=items[+b.dataset.buy];if(run.scrap<r.price){toast('고철이 부족합니다.');return}run.scrap-=r.price;takeReward(r,false);return}if(e.target.id==='shopHeal'){const price=Math.round(35*discount);if(run.scrap>=price){run.scrap-=price;run.player.hp=Math.min(run.player.maxHp,run.player.hp+25);toast('수리 완료')}}if(e.target.id==='shopLeave')openRoutes()}}
function openMedical(){const m=overlayHTML('의료실',`<div class="reward-grid"><button class="reward" data-med="heal"><h3>생명력 회복</h3><p>생명력 35 회복</p></button><button class="reward" data-med="shield"><h3>방어판 복구</h3><p>방어판 1개 복구</p></button><button class="reward rare" data-med="sacrifice"><h3>위험 수술</h3><p>최대 생명력 8 증가, 저주 +1</p></button></div>`);m.onclick=e=>{const b=e.target.closest('[data-med]');if(!b)return;if(b.dataset.med==='heal')run.player.hp=Math.min(run.player.maxHp,run.player.hp+35*(run.contracts.includes('low_heal')?.5:1));if(b.dataset.med==='shield')run.player.shield=Math.min(run.player.maxShield,run.player.shield+20);if(b.dataset.med==='sacrifice'){run.player.maxHp+=8;run.player.hp+=8;run.curse++}openRoutes()}}
function openCraft(){const cost=Math.round(40*(run.character.id==='mara'?.8:1));const m=overlayHTML('제작실',`<p>고철 ${run.scrap} · 개조 비용 ${cost}</p><div class="reward-grid"><button class="reward" data-craft="damage"><h3>총열 보정</h3><p>현재 런 피해 +8%</p></button><button class="reward" data-craft="reload"><h3>탄창 정비</h3><p>재장전 속도 +12%</p></button><button class="reward" data-craft="module"><h3>모듈 제작</h3><p>무작위 모듈 1개</p></button></div>`,`<button id="craftLeave">나가기</button>`);m.onclick=e=>{if(e.target.id==='craftLeave'){openRoutes();return}const b=e.target.closest('[data-craft]');if(!b)return;if(run.scrap<cost){toast('고철이 부족합니다.');return}run.scrap-=cost;if(b.dataset.craft==='damage')run.weapon.frame.damage*=1.08;if(b.dataset.craft==='reload')run.weapon.frame.reload*=.88;if(b.dataset.craft==='module'){const mod=pick(D.modules);run.modules.push({...mod,uid:`m${Date.now()}`,rotation:0,placed:false});unlockCodex('modules',mod.id);openInventory(true);return}openRoutes()}}
function openEvent(secret=false){const ev=secret?D.events.find(x=>x.id==='event8')||pick(D.events):pick(D.events.filter(x=>!run.eventFlags.includes(x.id)));run.eventFlags.push(ev.id);unlockCodex('events',ev.id);if(secret){run.memoryFragments++;run.bossKeys++;achievement('ach30')}const m=overlayHTML(secret?'비밀방: '+ev.name:ev.name,`<p>${ev.text}</p><div class="reward-grid">${ev.choices.map((c,i)=>`<button class="reward" data-choice="${i}"><h3>${c.label}</h3><p>${c.effect==='heal'?'회복':c.effect==='loot'?'희귀 보상':'저주와 높은 보상'}</p></button>`).join('')}</div>`);m.onclick=e=>{const b=e.target.closest('[data-choice]');if(!b)return;const c=ev.choices[+b.dataset.choice];if(c.effect==='heal')run.player.hp=Math.min(run.player.maxHp,run.player.hp+c.value);if(c.effect==='loot'){run.scrap+=40+c.value*10;const mod=pick(D.modules);run.modules.push({...mod,uid:`m${Date.now()}`,rotation:0,placed:false})}if(c.effect==='curse'){run.curse+=c.value;run.scrap+=80}openRoutes()}}
let invSelected=null,returnAfterBag=false;
function openInventory(fromReward=false){if(!run)return;returnAfterBag=fromReward;renderInventory();show('inventory')}
function rotatedShape(mod){let pts=mod.shape.map(([x,y])=>[x,y]);for(let r=0;r<(mod.rotation||0)%4;r++)pts=pts.map(([x,y])=>[-y,x]);const minX=Math.min(...pts.map(p=>p[0])),minY=Math.min(...pts.map(p=>p[1]));return pts.map(([x,y])=>[x-minX,y-minY])}
function renderInventory(){
 const connectorCells={0:'power',5:'signal',24:'ammo',29:'cool'};
 $('#bagGrid').innerHTML=Array.from({length:30},(_,i)=>`<div class="bag-cell ${connectorCells[i]||''}" data-cell="${i}">${run.bagBlocked.has(i)?'<div class="bag-item">봉쇄</div>':''}</div>`).join('');
 for(const mod of run.modules.filter(x=>x.placed)){
  for(const idx of mod.cells||[]){
   const cell=$(`.bag-cell[data-cell="${idx}"]`);
   if(cell)cell.innerHTML=`<button class="bag-item ${mod.connected?'connected':''}" data-uid="${mod.uid}">${mod.name}</button>`;
  }
 }
 $('#moduleTray').innerHTML=run.modules.map(m=>`<button class="module-chip ${invSelected===m.uid?'selected':''}" data-module="${m.uid}">${m.placed?'● ':'○ '}${m.name}<br><small>${m.desc}</small></button>`).join('');
 const s=effectiveStats();
 $('#buildStats').textContent=`무기: ${run.weapon.frame.name}\n총열: ${run.weapon.barrel.name}\n탄창: ${run.weapon.magazine.name}\n코어: ${run.weapon.core.name}\n피해 ${Math.round(s.damage)} · 발사 간격 ${s.rate.toFixed(2)}초 · 탄창 ${s.mag}\n전력 ${s.power}/${s.maxPower} · 중량 ${s.weight}/${s.maxWeight}\n활성 시너지: ${run.synergyIds.map(id=>D.synergies.find(x=>x.id===id)?.name).join(', ')||'없음'}`;
 $('#moduleTray').onclick=e=>{const b=e.target.closest('[data-module]');if(!b)return;invSelected=b.dataset.module;renderInventory()};
 $('#bagGrid').onclick=e=>{const cell=e.target.closest('[data-cell]');const item=e.target.closest('[data-uid]');if(item){const mod=run.modules.find(x=>x.uid===item.dataset.uid);if(mod){removeModule(mod);invSelected=mod.uid;renderInventory()}return}if(!cell||!invSelected)return;const mod=run.modules.find(x=>x.uid===invSelected);placeModule(mod,+cell.dataset.cell);renderInventory()};
 $('#rotateSelected').onclick=()=>{const m=run.modules.find(x=>x.uid===invSelected);if(m){if(m.placed)removeModule(m);m.rotation=(m.rotation+1)%4;renderInventory()}};
 $('#autoArrange').onclick=()=>{autoArrangeBag(true);renderInventory()};
 $('#applyBag').onclick=closeInventory;
 $('#closeBag').onclick=closeInventory;
}
function removeModule(mod){for(const i of mod.cells||[])if(run.bag[i]===mod.uid)run.bag[i]=null;mod.placed=false;mod.cells=[];mod.connected=false}