function damageEnemy(e,amount,strong=false,b=null){if(e.dead||e.inv>0)return 0;if(e.shield>0){const d=Math.min(e.shield,amount);e.shield-=d;amount-=d;if(amount<=0)return d}if(e.statuses.corrode)amount*=1+e.statuses.corrode*.06;if(e.statuses.freeze)amount*=1+e.statuses.freeze*.025;if(e.boss)amount*=effectiveStats().bossDamage||1;e.hp-=amount;run.damage+=amount;save.stats.damage+=amount;e.hit=.08;if(save.settings.damageNumbers)run.texts.push({x:e.x,y:e.y-20,t:.65,text:`${Math.round(amount)}${b?.crit?'!':''}`,color:b?.crit?'#ffe36e':'#fff'});if(strong)run.camera.shake=Math.max(run.camera.shake,4);if(e.hp<=0)killEnemy(e,b);return amount}
function killEnemy(e,b){if(e.dead)return;e.dead=true;run.kills++;save.stats.kills++;run.player.focus=Math.min(8,run.player.focus+1);burst(e.x,e.y,e.color||'#ff647b',e.boss?40:12);if(e.boss){achievement(`ach${Math.min(4,run.zone+1)}`);roomComplete(true)}else{if(run.weapon.magazine.id==='regen'&&rand()<.16)run.player.ammo=Math.min(effectiveStats().mag,run.player.ammo+1);if(effectiveStats().devour)run.devourBuff=Math.min(5,(run.devourBuff||0)+1);if(run.contracts.includes('death_bullets'))radialShots(e.x,e.y,6,150,8,'enemy');if(rand()<.28)run.pickups.push({kind:rand()<.78?'scrap':'heal',x:e.x,y:e.y,r:7,t:20,value:rand()<.78?2+Math.floor(rand()*5):3})}unlockCodex('enemies',e.id);if(run.kills===1)achievement('ach0');if(run.kills>=1000)achievement('ach12')}
function hurtPlayer(amount,source='enemy'){const p=run.player;if(p.inv>0||run.over)return;run.noHitRoom=false;p.focus=0;let left=amount;if(p.tempShield>0){const d=Math.min(p.tempShield,left);p.tempShield-=d;left-=d}if(left>0&&p.shield>0){const d=Math.min(p.shield,left);p.shield-=d;left-=d}if(left>0)p.hp-=left;p.inv=.75;p.hitFlash=.2;run.camera.shake=10;burst(p.x,p.y,'#ff4b67',18);run.lastDamageSource=source;tone(80,.15,'sawtooth',.05);if(p.hp<=0)endRun(false)}
function radialShots(x,y,count,speed,damage,team='enemy',offset=0){for(let i=0;i<count;i++){const a=offset+i/count*TAU;const b={x,y,px:x,py:y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:5,life:5,damage,team,color:team==='enemy'?'#ff627e':'#83f2ff'};(team==='enemy'?run.enemyBullets:run.bullets).push(b)}}
function aimedShot(e,speed=240,damage=e.damage,count=1,spread=.18){const target=run.decoy||run.player,a=Math.atan2(target.y-e.y,target.x-e.x);for(let i=0;i<count;i++){const ang=a+(i-(count-1)/2)*spread;run.enemyBullets.push({x:e.x,y:e.y,px:e.x,py:e.y,vx:Math.cos(ang)*speed,vy:Math.sin(ang)*speed,r:5,life:5,damage,team:'enemy',color:'#ff657f'})}}
function burst(x,y,color,count=8){for(let i=0;i<count;i++){const a=rand()*TAU,s=35+rand()*170;run.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,r:2+rand()*4,t:.25+rand()*.45,max:.7,color})}}
function update(dt){if(!run||run.paused||run.over||screen!=='game')return;dt=Math.min(dt,.033);run.elapsed+=dt;const p=run.player,s=effectiveStats();p.inv=Math.max(0,p.inv-dt);p.hitFlash=Math.max(0,p.hitFlash-dt);p.fireCd=Math.max(0,p.fireCd-dt);p.rollCd=Math.max(0,p.rollCd-dt);p.activeCd=Math.max(0,p.activeCd-dt);p.overheated=Math.max(0,p.overheated-dt);p.heat=Math.max(0,p.heat-dt*(p.overheated?18:10));p.focus=Math.max(0,p.focus-dt*.22);if(run.slowTime)run.slowTime=Math.max(0,run.slowTime-dt);if(run.gravityTime)run.gravityTime=Math.max(0,run.gravityTime-dt);if(run.overload)run.overload=Math.max(0,run.overload-dt);if(run.freeAmmo)run.freeAmmo=Math.max(0,run.freeAmmo-dt);
 const move=inputMove(),aim=inputAim();if(aim.x||aim.y){p.aimX=aim.x;p.aimY=aim.y}
 if(p.roll>0){p.roll-=dt;const mult=860*(s.rollDistance||1);p.x+=p.rollDir.x*mult*dt;p.y+=p.rollDir.y*mult*dt;if(p.roll<.18)p.inv=Math.max(p.inv,.08)}else{const targetV={x:move.x*p.speed*s.moveMult,y:move.y*p.speed*s.moveMult};p.vx=lerp(p.vx,targetV.x,1-Math.pow(.02,dt/.08));p.vy=lerp(p.vy,targetV.y,1-Math.pow(.02,dt/.08));p.x+=p.vx*dt;p.y+=p.vy*dt}
 collideWorld(p);if(p.reloading){p.reloadT+=dt*(p.reloadPerfect?4:1);if(p.reloadT>=s.reload)finishReload()}else if(isFiring())fire();
 updateBullets(dt);updateEnemies(dt);updatePickups(dt);updateEffects(dt);updateGimmicks(dt);if(run.turret)updateTurret(dt);if(run.cloneDrone)updateCloneDrone(dt);if(run.nanite){run.nanite.t-=dt;if(dist(p,run.nanite)<90)p.hp=Math.min(p.maxHp,p.hp+4*dt);if(run.nanite.t<=0)run.nanite=null}if(run.decoy&&(run.decoy.t-=dt)<=0)run.decoy=null;if(run.barrier&&(run.barrier.t-=dt)<=0)run.barrier=null;
 if(!run.roomClear&&!run.enemies.some(e=>!e.dead)){if(run.wave<run.waves){if(!run.pendingWave){run.pendingWave=true;setTimeout(()=>{if(run&&!run.roomClear)spawnWave()},450)}}else roomComplete(false)}updateHUD()}
function collideWorld(o){o.x=clamp(o.x,o.r+22,W-o.r-22);o.y=clamp(o.y,o.r+58,H-o.r-22);for(const r of run.obstacles){const cx=clamp(o.x,r.x,r.x+r.w),cy=clamp(o.y,r.y,r.y+r.h),dx=o.x-cx,dy=o.y-cy,d=Math.hypot(dx,dy);if(d<o.r&&d>0){o.x+=dx/d*(o.r-d);o.y+=dy/d*(o.r-d)}}}
function updateBullets(dt){
 const slow=run.slowTime?.45:1;for(let i=run.bullets.length-1;i>=0;i--){const b=run.bullets[i];b.px=b.x;b.py=b.y;if(b.homing){const t=nearestEnemy();if(t){const desired=Math.atan2(t.y-b.y,t.x-b.x),current=Math.atan2(b.vy,b.vx),a=current+angleDiff(desired,current)*b.homing;const sp=Math.hypot(b.vx,b.vy);b.vx=Math.cos(a)*sp;b.vy=Math.sin(a)*sp}}if(run.gravityTime){const gx=W/2,gy=H/2,d=norm(gx-b.x,gy-b.y);b.vx+=d.x*40*dt;b.vy+=d.y*40*dt}b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.returning&&b.life<.65){const d=norm(run.player.x-b.x,run.player.y-b.y),sp=Math.hypot(b.vx,b.vy);b.vx=d.x*sp;b.vy=d.y*sp}let remove=b.life<=0;if(!remove&&(b.x<18||b.x>W-18||b.y<52||b.y>H-18)){if(b.bounce>0){if(b.x<18||b.x>W-18)b.vx*=-1;if(b.y<52||b.y>H-18)b.vy*=-1;b.bounce--;b.x=clamp(b.x,19,W-19);b.y=clamp(b.y,53,H-19);b.damage*=1.2}else remove=true}for(const r of run.obstacles){if(b.x>r.x&&b.x<r.x+r.w&&b.y>r.y&&b.y<r.y+r.h){if(b.bounce>0){const dl=Math.abs(b.x-r.x),dr=Math.abs(b.x-(r.x+r.w)),dtp=Math.abs(b.y-r.y),db=Math.abs(b.y-(r.y+r.h)),mn=Math.min(dl,dr,dtp,db);if(mn===dl||mn===dr)b.vx*=-1;else b.vy*=-1;b.bounce--;b.damage*=1.2}else remove=true;break}}
 if(!remove){for(const e of run.enemies){if(e.dead)continue;if(Math.hypot(b.x-e.x,b.y-e.y)<b.r+e.r){damageEnemy(e,b.damage,b.crit,b);applyStatus(e,b.status);if(b.explosion)explode(b.x,b.y,b.explosion,b.damage*.65,'player');if(b.split)for(let k=0;k<b.split;k++)createBullet(b.x,b.y,Math.atan2(b.vy,b.vx)+(k?1:-1)*.5,{...effectiveStats(),damage:b.damage*.3,projectiles:1,split:0},1);if(b.clone&&rand()<b.clone)createBullet(b.x,b.y,Math.atan2(b.vy,b.vx)+(.4-rand()*.8),{...effectiveStats(),damage:b.damage*.55,projectiles:1},1);if(b.pierce>0){b.pierce--;b.damage*=.85}else remove=true;break}}}if(remove)run.bullets.splice(i,1)}