'use strict';
function roomComplete(boss){
 if(run.roomClear)return;run.roomClear=true;run.enemyBullets=[];run.totalRooms++;
 if(run.noHitRoom)achievement('ach9');
 if(boss){
  run.bossKeys++;run.scrap+=70+run.zone*25;
  if(run.enemies.some(e=>e.miniboss)){setTimeout(()=>openReward(true),700);return}
  if(run.mode==='bossrush'){
   if(run.zone<3){run.zone++;run.afterBossAction='boss';setTimeout(()=>openReward(true),700)}else setTimeout(()=>endRun(true,'basic'),900);return;
  }
  if(run.mode==='endless'){
   if(run.zone<3)run.zone++;else{run.zone=0;run.threat++;run.endlessLoop++;save.stats.bestEndless=Math.max(save.stats.bestEndless,run.endlessLoop)}
   run.roomIndex=0;run.afterBossAction='combat';setTimeout(()=>openReward(true),700);return;
  }
  if(run.zone<3){run.zone++;run.roomIndex=0;run.bagExpanded=Math.min(3,run.bagExpanded+1);run.afterBossAction='combat';toast('보스 격파 · 가방 확장');setTimeout(()=>openReward(true),700)}
  else if(run.zone===3)setTimeout(()=>endingDecision(),900);
  else setTimeout(()=>endRun(true,'truth'),900);
 }else{
  run.scrap+=12+Math.floor(rand()*12);run.roomIndex++;setTimeout(()=>openReward(false),650)
 }
 tone(760,.12,'triangle',.04)
}
function rewardRarity(){const r=rand()+run.threat*.015+run.curse*.01;return r>.96?'legendary':r>.78?'epic':r>.45?'rare':r>.18?'uncommon':'common'}
function makeReward(forceBoss=false){const rarity=forceBoss?'epic':rewardRarity();const types=forceBoss?['barrel','magazine','core','module','bag','maxhp']:['frame','barrel','magazine','core','module','active','scrap','heal','shield'];const type=pick(types);let item=null,name='',desc='';if(type==='frame'){item=pick(D.weapons);name=item.name;desc=item.desc}else if(type==='barrel'){item=pick(D.barrels);name=item.name;desc=item.tags.join(' · ')}else if(type==='magazine'){item=pick(D.magazines);name=item.name;desc=item.tags.join(' · ')}else if(type==='core'){item=pick(D.cores);name=item.name;desc=item.tags.join(' · ')}else if(type==='module'){item=pick(D.modules.filter(x=>x.rarity===rarity)||D.modules);name=item.name;desc=item.desc}else if(type==='active'){item=pick(D.actives);name=item.name;desc=item.desc}else if(type==='scrap'){name='고철 묶음';desc=`고철 ${35+run.zone*12} 획득`}else if(type==='heal'){name='의료 나노젤';desc='생명력 30 회복'}else if(type==='shield'){name='방어판';desc='방어판 1개 획득'}else if(type==='bag'){name='가방 확장 슬롯';desc='장비 가방 사용 가능 칸 1개 증가'}else{name='심장 강화';desc='최대 생명력 12 증가'}return {type,item,name,desc,rarity,id:`reward_${Date.now()}_${rand()}`}}
function openReward(forceBoss=false){const rewards=[makeReward(forceBoss),makeReward(forceBoss),makeReward(forceBoss)];$('#rewardTitle').textContent=forceBoss?'보스 회수품':'방 클리어 보상';$('#rewardCards').innerHTML=rewards.map((r,i)=>`<button class="reward ${r.rarity}" data-r="${i}"><span class="type">${r.type.toUpperCase()} · ${r.rarity.toUpperCase()}</span><h3>${r.name}</h3><p>${r.desc}</p><small>${r.item?.tags?.join(' / ')||'즉시 적용'}</small></button>`).join('');$('#rewardCards').onclick=e=>{const b=e.target.closest('[data-r]');if(!b)return;takeReward(rewards[+b.dataset.r],forceBoss)};show('reward')}
function takeReward(r,forceBoss){const p=run.player,s=effectiveStats();switch(r.type){case'frame':if(!run.contracts.includes('frame_lock')){run.weapon.frame={...r.item};p.ammo=r.item.mag;p.reserve=r.item.mag*10;unlockCodex('weapons',r.item.id)}else{run.scrap+=45;toast('프레임 고정 계약: 고철로 전환')}break;case'barrel':run.weapon.barrel={...r.item};unlockCodex('parts',r.item.id);break;case'magazine':run.weapon.magazine={...r.item};unlockCodex('parts',r.item.id);p.ammo=Math.min(p.ammo,effectiveStats().mag);break;case'core':run.weapon.core={...r.item};unlockCodex('parts',r.item.id);break;case'module':run.modules.push({...r.item,uid:`m${Date.now()}${rand()}`,rotation:0,placed:false});unlockCodex('modules',r.item.id);openInventory(true);return;case'active':run.active=r.item;break;case'scrap':run.scrap+=35+run.zone*12;break;case'heal':p.hp=Math.min(p.maxHp,p.hp+30*(run.contracts.includes('low_heal')?.5:1));break;case'shield':p.shield=Math.min(p.maxShield,p.shield+20);break;case'bag':run.bagExpanded=Math.min(3,run.bagExpanded+1);break;case'maxhp':p.maxHp+=12;p.hp+=12;break}checkSynergies();if(forceBoss&&run.afterBossAction){const action=run.afterBossAction;run.afterBossAction=null;loadRoom(action);show('game')}else if(forceBoss&&run.room?.kind==='elite'){openRoutes()}else openRoutes()}
function checkSynergies(){const tags=[...run.weapon.barrel.tags,...run.weapon.magazine.tags,...run.weapon.core.tags,...run.modules.filter(x=>x.placed).flatMap(x=>x.tags)];for(const syn of D.synergies){if(syn.tags.every(t=>tags.includes(t))&&!run.synergyIds.includes(syn.id)){run.synergyIds.push(syn.id);unlockCodex('synergies',syn.id);toast(`시너지 발견: ${syn.name}`,2200);tone(960,.16,'triangle',.04)}}if(run.synergyIds.length>=1)achievement('ach19');if(run.synergyIds.length>=10)achievement('ach20')}
function openRoutes(){const last=run.roomIndex>=run.roomsPerZone-1;if(last){loadRoom('boss');show('game');return}const candidates=[];if(run.roomIndex===Math.floor(run.roomsPerZone/2))candidates.push('elite');const pool=['combat','combat','shop','event','medical','craft','challenge','secret'];while(candidates.length<3){const k=pick(pool);if(!candidates.includes(k)||k==='combat')candidates.push(k)}const info={combat:['⚔','전투방','일반 보상'],elite:['☠','엘리트방','희귀 이상 보상'],shop:['¤','상점','구매·판매·새로고침'],event:['?','이벤트','선택과 결과'],medical:['✚','의료실','회복 또는 방어판'],craft:['⚒','제작실','부품 강화·분해'],challenge:['◆','도전방','고위험 고보상'],secret:['◈','비밀방','기억·설계도']};$('#routeCards').innerHTML=candidates.map((k,i)=>`<button class="route" data-route="${k}"><span class="icon">${info[k][0]}</span><span><b>${info[k][1]}</b><br><small>${info[k][2]}</small></span><span>위협 ${run.threat+(k==='elite'||k==='challenge'?1:0)}</span></button>`).join('');$('#routeCards').onclick=e=>{const b=e.target.closest('[data-route]');if(!b)return;chooseRoute(b.dataset.route)};show('route')}
function chooseRoute(kind){run.routeHistory.push(kind);if(kind==='shop')openShop();else if(kind==='event'||kind==='secret')openEvent(kind==='secret');else if(kind==='medical')openMedical();else if(kind==='craft')openCraft();else{loadRoom(kind==='challenge'?'elite':kind);show('game')}}
function overlayHTML(title,body,footer=''){const m=$('#overlayModal');m.innerHTML=`<header><div><p class="eyebrow">MORROW FACILITY</p><h2>${title}</h2></div></header>${body}<footer>${footer}</footer>`;show('overlay');return m}